### PR TITLE
Create airport list in CSV format

### PR DESCRIPTION
**Pull request by pyrog**
Took datas from aerolist.php,
clean them,
add column Country (took ICAO codes),
sort datas by country and by full name.

The idea is to separate code from datas…

### CODE REVIEW

**Comment by snip** [comment]
Have you tested this change before submitting it?
Why have you added this temporary file? "flightlog/.~lock.aerolist.csv"
Please correct and rebase.

**Comment by pyrog** [comment]
> Why have you added this temporary file? "flightlog/.~lock.aerolist.csv"
It was a mistake 😉 

Rebase done

**Comment by snip** [comment]
Where are u using this new csv file?
Please validate your code before submitting a pull request.

**Comment by pyrog** [comment]
> Where are u using this new csv file?
Please validate your code before submitting a pull request.

I will modify `aerolist.php` to load this file. It's not finish yet 😉

**Comment by snip** [comment]
Ok so please commit only when you have done & validated all the change.
There should be only one commit for a given change.

**Comment by snip** [comment]
Flightlog is no more supported.

**Pull request closed without merging**
